CREATE TABLE IF NOT EXISTS clips (
		id TEXT NOT NULL PRIMARY KEY,
        createTime DATETIME NOT NULL,
        localReference TEXT NOT NULL,
        cloudReference TEXT NOT NULL,
        storageProvider TEXT NOT NULL,
        capturer TEXT NOT NULL,
        camera TEXT NOT NULL,
        region TEXT NOT NULL,
        location TEXT NOT NULL,
        priority TEXT NOT NULL,
        frames INTEGER NOT NULL,
        recordingBeginTime DATETIME NOT NULL,
        recordingEndTime DATETIME NOT NULL,
        publishTime DATETIME NOT NULL,
        modelInvocationBeginTime DATETIME NOT NULL,
        modelInvocationEndTime DATETIME NOT NULL,
        alertInvocationBeginTime DATETIME NOT NULL,
        alertInvocationEndTime DATETIME NOT NULL,
        indexTime DATETIME NOT NULL,
        prevClip TEXT,
        analytics TEXT,
        alertTypes TEXT,
        mediaIndexerTypes TEXT,
        tags TEXT,
        tagsCount INTEGER NOT NULL DEFAULT 0,
        alertsCount INTEGER NOT NULL DEFAULT 0,
        modelInvoker TEXT,
        clipType INTEGER NOT NULL DEFAULT 0,
        recordingDuration INTEGER NOT NULL DEFAULT 0,
        modelInvocationDuration INTEGER NOT NULL DEFAULT 0,
        alertInvocationDuration INTEGER NOT NULL DEFAULT 0,
        create2IndexDuration INTEGER NOT NULL DEFAULT 0
    );	
